paths:
  static: public
  uploads: public/images/docsImages
  collections: content
collections_config:
  docs_cn_about:
    path: content/docs/cn/about
    name: 关于 (cn)
    icon: info
    url: /docs/about/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_cn_blog:
    path: content/docs/cn/blog
    name: Blog (cn)
    icon: videogame_asset
    url: /docs/blog/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_cn_docs:
    path: content/docs/cn/docs
    name: 文档 (cn)
    icon: docs
    url: /docs/docs/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_cn_notebook:
    path: content/docs/cn/notebook
    name: Notebook (cn)
    icon: book_4
    url: /docs/notebook/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_cn_works:
    path: content/docs/cn/works
    name: Rwagsu 的作品 (cn)
    icon: blender
    url: /docs/works/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_en_about:
    path: content/docs/en/about
    name: About (en)
    icon: info
    url: /docs/about/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_en_blog:
    path: content/docs/en/blog
    name: Blog (en)
    icon: videogame_asset
    url: /docs/blog/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_en_docs:
    path: content/docs/en/docs
    name: Docs (en)
    icon: docs
    url: /docs/docs/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_en_notebook:
    path: content/docs/en/notebook
    name: Notebook (en)
    icon: dock_to_bottom
    url: /docs/notebook/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  docs_en_works:
    path: content/docs/en/works
    name: Rwagsu's Works
    icon: blender
    url: /docs/works/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/docs.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
_inputs:
  date:
    comment: 文档发布日期
    instance_value: now
    cascade: true
timezone: Asia/Shanghai
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
