name: "在网站添加友链"
description: "请求将你的网站添加到友链页面."
title: "[友链请求]"
labels: ["FriendlyLink Request"]

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > 由于一些原因, 友链仅对与 Rwagsu 交流过的用户开放.
        > (毕竟每天审查一堆认都不认识的用户整的链接, 或者谁搞了什么离谱东西, 会疯的 (っ °Д °;)っ)
        你的申请在  [Project](https://github.com/users/Rwagsu/projects/1) 呆一段时间后将被添加到  [友链页面](http://rwagsu.top/about/friendship_links) 中 ;)
        (。・∀・)ノ

  - type: checkboxes
    id: check
    attributes:
      label: 你有检查过你的表单吗?
      description: 不符合表单要求的申请会被直接关闭.
      options:
        - label: 我未在 [友链页面](http://rwagsu.top/about/friendship_links) 和 [Project](https://github.com/users/Rwagsu/projects/1) 中找到一模一样的链接, 且确定这是我自己的链接.
          required: true

        - label: 我知道该 issue 将对所有人公开, 无论如何都不会透露自己的个人 / 私密信息.
          required: true

        - label: 我知道只有与 Rwagsu 交流才能添加友链.
          required: true

        - label: 如果可以, 我想要被添加到 Starred.

  - type: input
    id: website
    attributes:
      label: 网站链接
      description: "你的网站"
      placeholder: "https://example.com"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 如何装饰你的卡片?
        Rwagsu 会尽可能在一张卡片中塞下你要的内容.

  - type: input
    id: title
    attributes:
      label: title (标题)
      description: "卡片的标题"
      placeholder: "例如: Rwagsu 的 Blog!"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: description (描述)
      description: "别太长拜托QAQ"
      placeholder: "例如: 是一个 Blog x)"
    validations:
      required: true

  - type: input
    id: cta
    attributes:
      label: cta (访问链接的文本)
      description: "不指定就默认的()"
      placeholder: "默认: 访问此网站!"

  - type: input
    id: iconSrc
    attributes:
      label: iconSrc (图标链接)
      description: "需要一个图片链接, 当未指定或加载失败时显示 iconFallBack (指定一个吧! QAQ)"
      placeholder: "https://example.com/icon.png"

  - type: input
    id: iconFallback
    attributes:
      label: iconFallBack (当 iconSrc 未指定或加载失败时显示的字符或图标)
      description: "需要一个字符 (或者 Emoji), 或者来自 [react-icons](https://react-icons.github.io/react-icons/) / [Lucide Icons](https://lucide.dev/) / [Iconify](https://icon-sets.iconify.design/) 的图标名称, 甚至是一个图片链接也可以."
      placeholder: "默认: 你的 title 的第一个字符 (如果是中文就是第一个字符的拼音的第一个字符)"

  - type: input
    id: iconFallbackColor
    attributes:
      label: iconFallbackColor (显示 iconFallBack 时的图标的背景色)
      description: "需要是 [RadixUI Colors](https://www.radix-ui.com/themes/docs/theme/color) 中支持的 Accents 颜色."
      placeholder: "默认: blue"

  - type: input
    id: tag
    attributes:
      label: tag (标签)
      description: "你可以在[友情链接](https://rwagsu.top/docs/about/friendly_links)页面看到现有的标签, 你也可以添加新的标签, 但当标签的意思与现有标签相似, 标签将被合并."
      placeholder: "例如: Blog"
    validations:
      required: true

  - type: input
    id: background
    attributes:
      label: background (背景)
      description: "可以是一个十六进制色号, 或者一个图片链接."
      placeholder: "默认: #0077FF 纯色背景"
  
  - type: textarea
    id: find
    attributes:
      label: 如何联系你?
      description: |
        既然认识你应该也可以让我联系到的吧😅

        千万别把你私人邮箱什么的写上去啊啊啊 Σ(っ °Д °;)っ

        让我能联系到你就行了w
      placeholder: "让我看看!"
    validations:
      required: true