name: "在网站添加友链"
description: "请求将你的网站添加到友链页面."
title: "[友链请求]"
labels: ["FriendlyLink Request"]

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > 由于一些原因, 友链仅对与 Rwagsu 交流过的用户开放.
        > (毕竟每天审查一堆认都不认识的用户整的链接, 会疯的 (っ °Д °;)っ)
        你的申请在  [Project](https://github.com/users/Rwagsu/projects/1) 呆一段时间后将被添加到  [友链页面](http://rwagsu.top/about/friendship_links) 中 ;)
        喵(

  - type: checkboxes
    id: check
    attributes:
      label: 你有检查过你的表单吗?
      description: 不符合表单要求的申请会被直接关闭.
      options:
        - label: 我未在 [友链页面](http://rwagsu.top/about/friendship_links) 和 [Project](https://github.com/users/Rwagsu/projects/1) 中找到一模一样的链接, 且确定这是我自己的链接.
          required: true

        - label: 我知道该 issue 将对所有人公开, 无论如何都不会透露自己的个人 / 私密信息.
          required: true

        - label: 我知道只有与 Rwagsu 交流才能添加友链.
          required: true

        - label: 如果可以, 我想要被添加到 Starred.

  - type: input
    id: website
    attributes:
      label: 网站链接
      description: "你的网站"
      placeholder: "https://example.com"
    validations:
      required: true

  - type: textarea
    id: card
    attributes:
      label: 如何装饰你的卡片?
      description: |
        Rwagsu 会尽可能在一张卡片中塞下你要的内容.

        目前支持添加:

        icon (图标, 但确保你的图标是从 [icones](https://icones.js.org/) 找到的图标, 且应提供类似 `tabler:brand-bandlab` 的图标唯一标识符.), 或者使用 Emoji 表情或提供图片链接.
        
        title (标题),

        description (描述),

        links (是的, 你可以添加更多链接, 但一个链接必须附上一个从 [icones](https://icones.js.org/) 找到的图标, 或 Emoji.)
      placeholder: 祝你好运 ;)
    validations:
      required: true
  
  - type: textarea
    id: find
    attributes:
      label: 如何联系你?
      description: |
        既然认识你应该也可以让我联系到的吧😅

        千万别把你私人邮箱什么的写上去啊啊啊 Σ(っ °Д °;)っ

        让我能联系到你就行了w
      placeholder: "让我看看!"
    validations:
      required: true